<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="ADOE-20150303CS" ignored="0" name="Test" tests="19" failures="1" timestamp="22 十一月 2018 06:03:17 GMT" time="4.074" errors="0">
  <testcase name="f" time="1.205" classname="com.yy.test.NewTest"/>
  <testcase name="f" time="0.123" classname="com.yy.test.NewTest"/>
  <testcase name="f" time="0.134" classname="com.yy.test.NewTest"/>
  <testcase name="f" time="0.11" classname="com.yy.test.NewTest"/>
  <testcase name="f" time="0.129" classname="com.yy.test.NewTest"/>
  <testcase name="f" time="0.117" classname="com.yy.test.NewTest"/>
  <testcase name="f" time="0.113" classname="com.yy.test.NewTest"/>
  <testcase name="f" time="0.121" classname="com.yy.test.NewTest"/>
  <testcase name="f" time="0.121" classname="com.yy.test.NewTest"/>
  <testcase name="f" time="0.133" classname="com.yy.test.NewTest"/>
  <testcase name="f" time="0.104" classname="com.yy.test.NewTest"/>
  <testcase name="f" time="0.113" classname="com.yy.test.NewTest"/>
  <testcase name="f" time="0.109" classname="com.yy.test.NewTest"/>
  <testcase name="f" time="0.121" classname="com.yy.test.NewTest"/>
  <testcase name="test1" time="0.008" classname="com.yy.test.NewTest"/>
  <testcase name="test2" time="0.004" classname="com.yy.test.NewTest"/>
  <testcase name="test3" time="0.0" classname="com.yy.test.NewTest">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase name="test3" time="0.0" classname="com.yy.test.NewTest">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase name="test3" time="0.004" classname="com.yy.test.NewTest">
    <failure type="java.lang.AssertionError" message="expected [1] but found [2]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [2]
at com.yy.test.NewTest.test3(NewTest.java:36)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
</testsuite> <!-- Test -->
